import type { Metadata, Viewport } from "next"
import {
  Inter,
  Caveat,
  Permanent_Marker,
  Source_Code_Pro,
} from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Inspirational Quote Generator",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
